apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helloworld-helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: haze5991/myapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
            
